# Site settings
title: rojcyk
description: "Over the past 2 years, I’ve been designing apps for various startups and businesses from around the globe. I would like to share with you what I’ve learned during the time and help you improve your products and the process behind creating them."
name: Denis Rojcyk
email: denis@rojcyk.com

baseurl: "" # the subpath of your site, e.g. /blog/
url: "0.0.0.0:4000" # the base hostname & protocol for your site

# Social
twitter:    rojcyk
linkedin:   rojcyk
github:     rojcyk
dribbble:   rojcyk
google:     "112429095045485299421"

# Build settings
markdown: kramdown
