# Site settings
title: "1 per Week"
email: michal@tapmates.com
description: "Once a week we publish articles that help you make your life easier using iOS and Mac apps in various situations."
baseurl: ""
url: "http://1perweek.com"

baseurl: "" # the subpath of your site, e.g. /blog/

# Social
twitter:    1pweek
facebook:   1perweek


# Build settings
markdown: kramdown
